name: Verify Pull Request

on:
  pull_request:
    branches: main

jobs:
  build:
    name: Build Library and check size
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: pnpm run build
        run: pnpm run build
        env:
          CI: true
      # - name: pnpm run size
      #   run: pnpm run size

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: pnpm run lint
        run: pnpm run lint
        env:
          CI: true

  test:
    name: Run unit tests and check coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      # - name: pnpm run test:coverage
      #   run: pnpm run test:coverage
      #   env:
      #     CI: true
      - name: pnpm run test
        run: pnpm run test
        env:
          CI: true

  # build-docs:
  #   name: Build docs
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - uses: ./.github/actions/setup-env
  #     - name: pnpm run docs:build
  #       run: pnpm run docs:build
  #       env:
  #         CI: true

  commitlint:
    name: Check commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: pnpm run commitlint
        env:
          BASE_REF: origin/${{ github.base_ref }}
          HEAD_REF: origin/${{ github.head_ref }}
        run: pnpm run commitlint --from $(git merge-base --octopus ${{ env.BASE_REF }} ${{ env.HEAD_REF }}) --to $(git rev-parse ${{ env.HEAD_REF }})

  spell-check:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: pnpm run spellcheck
        run: pnpm run spellcheck
